# Generated by Django 2.2.5 on 2021-02-05 01:03

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_auto_20210205_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='이름')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='성')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일 주소')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, upload_to='', verbose_name='프로필 사진')),
                ('gender', models.CharField(blank=True, choices=[('male', '남자'), ('female', '여자'), ('other', '기타')], max_length=10, verbose_name='성별')),
                ('bio', models.TextField(blank=True, verbose_name='자기 소개')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='생일')),
                ('language', models.CharField(blank=True, choices=[('en', '영어'), ('kr', '한국어')], max_length=2, verbose_name='사용하는 언어')),
                ('currency', models.CharField(blank=True, choices=[('usd', '달러'), ('krw', '원')], help_text='사용하는 통화를 선택하세요', max_length=3, verbose_name='통화 선택')),
                ('superhost', models.BooleanField(default=False, verbose_name='슈퍼 호스트')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
